### ISSUE TITLE
Deprecate Morebits.wiki.* and create a new library

### ISSUE THREAD

**Issue by siddharthvp** [wikimedia-gadgets/twinkle#1029]
Morebits.wiki.* has descended into a spaghetti mess over the years. IMO, what we should do is to deprecate the whole thing and start afresh. I would propose the creation of a new library called `<insert cool name here>` (codenamed senora for the sake of talking about it below) with some much-needed enhancements.

Problems with morebits:
- The user agent string is a nasty global. This makes it unsuitable for use by multiple scripts simultaneously. The approach I used in my [DYK-helper](https://en.wikipedia.org/wiki/User:SD0001/DYK-helper.js) and other morebits-based scripts is to avoid over-writing the global user-agent until we're certain the user is about to make an edit. Hardly nice.
- No ability to add a default edit summary or default change tags. 
- Has used the old-fashioned callbacks all this while. #911 is an attempt to fix but it would be good to get rid of callback support as a whole.
- The Morebits.wiki.actionCompleted.* system is hacky and confusing and unreliable. 
- Error callbacks generally take the page object as argument, which is an anti-pattern. Generally, most libraries would use an error object or error code.
- Morebits.wiki.api:
  - a pathetic constructor
  - uses POST requests all the time even when GET is suitable
    - the function to make the requests is called `post()`! So it would be silly to rework it use GET. 
  - doesn't retry on badtoken errors

The solution:
- senora would be a class that needs to be instantiated to access all the functionality.
  - created like `var sen = new Senora('twinkle ([[w:en:TW]]');` (takes the user agent as constructor argument).
  - This would enable each script to create a senora instance with a user agent string, an edit summary advert, and change tags used in every write API call. Presently Twinkle source code is littered with a gazillion instance of ` + Twinkle.getPref('summaryAd')` which is unnecessary.
  - This also eliminates the need of having `Morebits.wiki.actionCompleted.*` stuff around as globals (shared between scripts). They would be class attributes instead. 
- senora's api class would be an extension of `mw.Api` integrated into the status system.
  - mw.Api is better at pre-processing parameters, eg. it scrubs out any `false` or `undefined` params.
  - mw.Api's postWithToken automatically handles badtoken retries.
  - mw.Api has an `abort` method to cancel all in-progress requests made using the object. This provides a way to solve #124. 
  - mw.Api's behaviour of getting a new token for every edit is a no-no for us that we'll probably want to customise. 
  - cleanly integrating with the status system would be a challenge.
- senora's page class would be a subclass of `mw.Title`. It would thus natively support methods like `getTalkPage()`. 
- The API and page objects can be created in short as `new sen.api()` and `new sen.page()` rather than the long-winded `new Morebits.wiki.page()`. 
- I don't see any problems with `Morebits.status`, other than that it's cruftily written, so probably can be imported as is. 

If this is developed, it should be done with unit tests and on-wiki documentation from the start itself. 

Also if we do this, there'd be no need for #911 (the code can be reused though, it's not that the effort on that has went to waste). 

IMO this would be a fun project to undertake.

**Comment by DannyS712** [comment]
> senora's api class would be an extension of `mw.Api`
> senora's page class would be a subclass of `mw.Title`

how exactly do you plan on doing this without using `OO.inheritClass`? Is there another way to add subclasses?
If we are going to be loading oojs after this, it'll make things easier to refactor without needing to use typescript :)

**Comment by siddharthvp** [comment]
Was mostly just thinking out loud rather than have implementation plans ...

**Comment by siddharthvp** [comment]
No bandwidth to work on this. Please reopen if someone wants to work on this or thinks this is a good idea.
