### ISSUE TITLE
tag: Add validations to redirect tags

### ISSUE THREAD

**Issue by Amorymeltzer** [wikimedia-gadgets/twinkle#1037]
From https://github.com/azatoth/twinkle/pull/1002#issuecomment-651451863:

>One thing to consider is whether there is/are any validations that should be done.

>The short answer is yes: there are plenty that conflict (e.g. `{{R printworthy}}` and `{{R unprintworthy}}`) but the long answer is it's complex and we should only try to handle the obvious cases.

**Comment by NovemLinguae** [comment]
Would probably be easy to code the case mentioned. Any other obvious cases come to mind that we'd like to include? CC @sdkb since you seem to do a decent amount of redirect tagging.

**Comment by sdkb** [comment]
Validations sound good! Multiple "to [namespace]" tags or combining "from subtopic" and "to subtopic" would be another example. I wouldn't say I'm particularly involved in redirect tagging—I try to do it for my own redirects, but overall I view it as largely busywork of questionable value that is ripe for automation.
