### ISSUE TITLE
Add {{find sources}} links for AfD and PROD

### ISSUE THREAD

**Issue by siddharthvp** [wikimedia-gadgets/twinkle#1047]
This should help with performing a WP:BEFORE. Inspired by [this discussion](https://en.wikipedia.org/wiki/Wikipedia_talk:Proposed_deletion#RfC_on_improving_PROD_instructions_in_%22Before_nomination%22_section). 

Regarding implementation, should we just API:Parse the {{find sources}} template? This will be easier but the links would take time to appear. A more elegant implementation would be translate the template to javascript. A bit more code but the IMO this would be proper way of doing it.

**Comment by siddharthvp** [comment]
Opened 1047. Hadn't planned to do this myself. But I came across [another discussion](https://en.wikipedia.org/wiki/Wikipedia_talk:Articles_for_deletion#WP:BEFORE_is_not_a_core_content_policy) on (the lack of use of) BEFORE, suggesting that this might be worth the effort (see comments by Aymatth2 et al).

**Comment by Amorymeltzer** [comment]
How slow, really?  Given that (especially for XfD) the user will be entering a reason and selecting some options, the wait for the parse query to load isn't long.  As long as we're not requerying every menu change, it shouldn't be too bad?

**Comment by Amorymeltzer** [comment]
Since it's just a template, couldn't we even just use `Morebits.wiki.preview`?  Might want to `.removeClass` but should work?

**Comment by siddharthvp** [comment]
For the record, agreed it's better to use API:Parse.

**Comment by Amorymeltzer** [comment]
Note: Above was done in #1280
