### ISSUE TITLE
Shouldn't try to file invalid requested moves

### ISSUE THREAD

**Issue by pppery** [wikimedia-gadgets/twinkle#1109]
[Requested move of a user page proposed using Twinkle that resulted in a template error](https://en.wikipedia.org/w/index.php?title=User_talk:Nplz&oldid=974068532)

Twinkle should presumably report that error to the user, instead of saving it to the page.

**Comment by Amorymeltzer** [comment]
There are a number of [error messages](https://en.wikipedia.org/wiki/Template:Requested_move#Error_messages) in the template, and this does seem like a good one to incorporate.  After #1033, though, the draft/userspace error is a bit more annoying, 'cause a technical RM *can* be used in those namespaces, right?
