### ISSUE TITLE
Move twinkle to a GitHub organisation

### ISSUE THREAD

**Issue by siddharthvp** [wikimedia-gadgets/twinkle#1140]
Suggested by @atlight in https://github.com/azatoth/twinkle/issues/129#issuecomment-702759024. 

Should we move twinkle to a new organisation called "en-wikipedia-gadgets"? I think that would be great as we could also host other gadgets without a single-owner such as popups over there. I have wanted to contribute to [popups](https://en.wikipedia.org/wiki/MediaWiki:Gadget-popups.js) -- but it's so difficult to get code reviews for any big changes due to lack of a repository.

**Comment by MusikAnimal** [comment]
Maybe "wikimedia-gadgets", or even "wikimedia-scripts"? Hopefully one day Twinkle will be global, and other gadgets like Popups could be too.

**Comment by MusikAnimal** [comment]
I would be happy to migrate [MoreMenu](https://github.com/MusikAnimal/MoreMenu) to the org. I am the sole author, but that's not by choice. In my view, once a script becomes a gadget, especially if it's "global" (used on many wikis), it's sort of in the community's hands since any int-admin can make changes to the deployed code.

**Comment by Amorymeltzer** [comment]
Would be neat, although if we’re thinking about a broader (en)wiki gadget org, it should primarily be discussed and organized on-wiki.

It’d be nice to have a centralized(ish) place for reviews ([T71445](https://phabricator.wikimedia.org/T71445) is a long way off) but I’m not certain how it’ll be perceived, what with requiring another account, etc.  Twinkle and MoreMenu would be on-board, and @enterprisey and @evad37 are obvious candidates, but I can see folks objecting to taking things like popups off-wiki (even if it’d be for the better (Also, oi does popups need some love)).

That being said, I think at the very least *Twinkle* could be made into an organization @azatoth.  I’ve thought about asking a few times, if only for some stuff around actions/security/etc.

**Comment by DannyS712** [comment]
Agree that having a centralized(ish) place for reviewers would be nice, but also that another account might not be the best idea. Perhaps use gerrit?

**Comment by siddharthvp** [comment]
I boldly went ahead and created a "wikimedia-gadgets" org, seeing that there hasn't been any activity here for a while, and because it seemed like a nice home for [types-mediawiki](https://github.com/wikimedia-gadgets/types-mediawiki). Will send out invitations shortly. I don't think there's a need to discuss on-wiki as it'd all be unofficial (either way) and even for gadgets that are added there, there's nothing preventing users from making bug reports or even edit requests on-wiki.

**Comment by azatoth** [comment]
> I boldly went ahead and created a "wikimedia-gadgets" org, seeing that there hasn't been any activity here for a while, and because it seemed like a nice home for [types-mediawiki](https://github.com/wikimedia-gadgets/types-mediawiki). Will send out invitations shortly. I don't think there's a need to discuss on-wiki as it'd all be unofficial (either way) and even for gadgets that are added there, there's nothing preventing users from making bug reports or even edit requests on-wiki.

I don't have anything against moving the repo, I was just uncertain if it was proper to name the org with wikimedia/wikipedia, so I never created a org;
But as we now have that org created, I can transfer it at any time. Just tell me when.

**Comment by MusikAnimal** [comment]
I already transferred [MoreMenu](https://github.com/wikimedia-gadgets/MoreMenu) :) @azatoth I would say there's no real consequence to moving Twinkle over now, if you're okay with it. We can make an effort to update links but they all forward automatically anyway (including git fetch/push URLs).

Thanks for starting this, @siddharthvp ! I'll help spread the word.

**Comment by azatoth** [comment]
moved!
