### ISSUE TITLE
Option for IPv6 blocks to include the /64 range

### ISSUE THREAD

**Issue by CaptainEek** [wikimedia-gadgets/twinkle#1173]
Feature request. English admin here, was just blocking an IPv6 user, and was thinking how convenient it would be if one could simply check a box in the blocking interface to block the /64 when dealing with IPv6 users. Since IPv6 allocations are so large, I almost always block the /64 range, but find it annoying that I have to go to the non-Twinkle block interface and manually add the /64. I suspect I am not alone in this. For a more detailed reasoning on blocking the 64, see https://en.wikipedia.org/wiki/User:TonyBallioni/Just_block_the_/64

This of course would require Twinkle to contextually know when its dealing with an IPv6, and display a relevant option only in those cases.

**Comment by L235** [comment]
As another enwiki admin I can say this would be a tremendous help

**Comment by siddharthvp** [comment]
Related: #775, #924

**Comment by ToBeFree** [comment]
This would be wonderful. Thanks Amory for working on this
