### ISSUE TITLE
Modal says "level 2 warning" when placing level 1 warning

### ISSUE THREAD

**Issue by RedDragonWebDesign** [wikimedia-gadgets/twinkle#1292]
Steps to reproduce:

- Go to an uncreated talk page.
- Place a level 1 vandalism warning.
- Modal pops up that says something like "No level 2 warning detected for this month, creating heading"

The level 2 part should correspond to the actual level of the warning.

**Comment by Amorymeltzer** [comment]
What is says is:

>Will create a new level 2 heading for the date, as none was found for this month

That's referring to the level of the heading i.e. `== Heading ==`

**Comment by RedDragonWebDesign** [comment]
Ah. My mistake. You could remove "level 2" for increased clarity, or leave as is.

**Comment by molly** [comment]
Perhaps rewording it to "Will create a new talk page section for this month, as none was found" would be a little clearer?

**Comment by Amorymeltzer** [comment]
> Perhaps rewording it to "Will create a new talk page section for this month, as none was found" would be a little clearer?

Yeah, I think that's much better; wikitext markup is a weird thing to reference.  You wanna open that @molly?  There's one in the block modules as well.
