### ISSUE TITLE
Morebits documentation gives a 404

### ISSUE THREAD

**Issue by sarthakkundra** [wikimedia-gadgets/twinkle#1299]
I was looking around the project trying to find some docs to understand the project so went to the repo's wiki. The link in the Wiki "Morebits Documentation" returns a 404. As someone new I don't know where it should lead to or if it's needed there or not but it should definitely not return a 404.

Steps to reproduce: 
1) Head to the repo's Wiki (3rd option from the right on the top panel).
2) Click on the "Morebits Documentation" link.
3) Land at a 404 Github page.

If someone can tell what's needed to be done here. I'll be happy to fix it.

**Comment by Amorymeltzer** [comment]
Oof, thanks!  Should be fixed now!  Link was pointing to the wrong directory

**Comment by sarthakkundra** [comment]
@Amorymeltzer While you're here can you guide me to the docs to setup the project locally? That'll be a huge help. Thanks!

**Comment by Amorymeltzer** [comment]
Sorry @sarthakkundra, do you mean in git?  There's a brief rundown in [CONTRIBUTING.md](https://github.com/wikimedia-gadgets/twinkle/blob/master/CONTRIBUTING.md#getting-started), but if you follow the steps at https://docs.github.com/en/github/getting-started-with-github/fork-a-repo you should be able to get set up locally.
