### ISSUE TITLE
protect: Watching expiry for rpp

### ISSUE THREAD

**Issue by Xi-Plus** [wikimedia-gadgets/twinkle#1315]
https://github.com/wikimedia-gadgets/twinkle/blob/2e5954a40eab5a58f6c139d95f574c13f95c7cf7/modules/twinkleprotect.js#L1516-L1535
`pageobj` is `Wikipedia:Requests for page protection`.
So you decide whether to set the expiry for **article** by checking **rppPage**'s watching status?

**Comment by Amorymeltzer** [comment]
Ugh yes that's very wrong.  I opened #1316 real quick, but I'm heading out atm, that look right to you?
