### ISSUE TITLE
Add preferences to dropdown menu?

### ISSUE THREAD

**Issue by RedDragonWebDesign** [wikimedia-gadgets/twinkle#1326]
Just a suggestion. Consider adding "Prefs" (preferences) to the Twinkle dropdown menu, at the bottom. That seems like an intuitive spot for it. It would point to the page Wikipedia:Twinkle/Preferences, so you wouldn't have to type WP:TWINKLE and click the link at the top, which is more steps than ideal.

**Comment by Amorymeltzer** [comment]
Semantically, wouldn't this be weird or confusing?  For non-Vector users, it'd take up valuable space, but even for Vector, it's a weird jump away.  There's now a link in every Twinkle window, though.
