### ISSUE TITLE
Support for {{Proposed deletion endorsed}}

### ISSUE THREAD

**Issue by RedDragonWebDesign** [wikimedia-gadgets/twinkle#1336]
So apparently there is a template for endorsing a proposed deletion (PROD) that somebody else did. Consider adding support for this template in Twinkle. Perhaps as a 3rd option in the PROD modal.

Example use of the template: https://en.wikipedia.org/w/index.php?title=Python_practice&oldid=1008751322

Example code of the template (goes right beneath the {{Proposed deletion/dated}} template):

````
{{Proposed deletion endorsed|1=Clearly not encyclopedic material per nomination. Not quite [[WP:A1|A1]] or [[WP:A3|A3]], though.}}
````

**Comment by siddharthvp** [comment]
It's already supported. Try PRODing a page that already has a PROD on it.
