### ISSUE TITLE
Prod sometimes makes edits logged out, fails to make edits, or deletes old prod log entries

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1376]
Sorry, this is probably hard to reproduce. But here are the diffs.

Editing while logged out, despite being logged in:

* https://en.wikipedia.org/w/index.php?title=User:Novem_Linguae/PROD_log&diff=1015435536&oldid=1013956253
* https://en.wikipedia.org/w/index.php?title=User:Novem_Linguae/PROD_log&diff=1013751263&oldid=1012932613
* https://en.wikipedia.org/w/index.php?title=User:Novem_Linguae/PROD_log&diff=1010387455&oldid=1010279789

Logging the prod in my prod log, but failing to tag the article or the user talk page

* https://en.wikipedia.org/w/index.php?title=User:Novem_Linguae/PROD_log&type=revision&diff=1015435536&oldid=1013956253&diffmode=source

Randomly deleted one of my other prods from the prod log

* https://en.wikipedia.org/w/index.php?title=User:Novem_Linguae/PROD_log&type=revision&diff=1015435536&oldid=1013956253&diffmode=source

**Comment by siddharthvp** [comment]
Is that even your IP address to begin with? None of those edits appear to have been made by Twinkle. They don't have the standard edit summary or change tag. Twinkle sends all its API queries with assert=user flag, so it isn't really possible for any edits to get saved logged out. You don't seem to have made any edits around the time of the IP's 1st and 3rd edits, which makes it look like this IP took a likening to editing your PROD log for whatever reason.

**Comment by NovemLinguae** [comment]
@siddharthvp I think you're right. I'll close this ticket. Thank you for your insight.
