### ISSUE TITLE
New maintenance plan

### ISSUE THREAD

**Issue by siddharthvp** [wikimedia-gadgets/twinkle#1381]
With Amorymeltzer deciding to leave and per https://github.com/wikimedia-gadgets/twinkle/issues/1375#issuecomment-817382361, I am proposing the following plan to continue maintenance of this repository. 

- As far as possible I'll avoid making code changes myself except for critical bugs or minor morebits changes that may be needed to get twinkle-core off the ground. Instead I'll restrict my involvement to reviewing and merging any PRs others open. I'll continue to be active on WT:TW where I'll try to get people involved here, since I myself certainly don't expect to stick around long-term.
  - If/when we start using twinkle-core here, then I may contribute more actively.
- A `release` branch is created which is ideally kept in sync with enwiki. The existing `master` branch continues to be the main branch which is the target of all PRs. I (or another maintainer) will move commits from `master` to `release` after a final round of testing.
- The useless "Enhancement" tag is deleted as every issue/PR is intended to be an enhancement.
- New tags "needs details or plan", "needs code", "good first task", "needs consensus" are created to label the issues/PRs so they're easily distinguishable for potential new contributors.
- I'll leave it up to @MusikAnimal on when to update the enwiki gadget pages. For my part I'll keep the `release` branch in deployment-ready state at all times.

Sounds good @MusikAnimal @atlight ?

**Comment by atlight** [comment]
> * The useless "Enhancement" tag is deleted as every issue/PR is intended to be an enhancement.

A better name would be "feature request". In Bugzilla (in use before Phabricator came along) there is a severity level called "enhancement" which was for bugs which didn't represent actual defects in the software, but were asking for new work to be done. That is why the label is named in that somewhat misleading way.

The rest of the plan looks good to me, so long as progress of some kind (however slow) is being made towards rolling out twinkle-core/twinkle-enwiki.

**Comment by siddharthvp** [comment]
Creation of `release` branch wasn't done eventually (seems unnecessary).
