### ISSUE TITLE
Make [vandalism] rollback links properly hideable via CSS

### ISSUE THREAD

**Issue by ToBeFree** [wikimedia-gadgets/twinkle#1386]
Instead of an external stylesheet, Twinkle uses inline CSS for the rollback links. This can be fine, but leads to issues when attempting to hide specific elements using CSS selectors in one's Special:MyPage/common.css.

A practical example that affects me: I currently (attempt to) use the following code to hide the red `[vandalism]` rollback link in favor of the MediaWiki core rollback link (which has a convenient JavaScript-based confirmation feature and is still faster at pushing the change to the database on large pages).

My custom CSS:

```
/* Hide Twinkle's "rollback" and "vandalism" links in favor of core rollback link in Special:Contributions */
.mw-special-Contributions .mw-contributions-current strong>a {
    display: none;
}

/* Hide Twinkle's (non-warning, instant-revert, default-summary) "vandalism" link in favor of the core rollback link above diffs */
.diff #tw-revert strong:nth-child(3) {
	display: none;
}
```

These CSS selectors are pretty far-fetched. MediaWiki is full of classes and IDs, Twinkle lacks them. However, I'd even use my code if it worked. It doesn't:

![twinkle-selectors-issue-20210417](https://user-images.githubusercontent.com/66693882/115122340-b639b980-9fb7-11eb-9309-90d2a3ccf567.png)

The very least I need is a workaround to remove the two pipes between the blue "rollback" and the red "vandalism" link above diffs.

**Comment by siddharthvp** [comment]
For contributions, you may want to use `.mw-special-Contributions [id^=tw-revert] strong` as what you have isn't twinkle-specific.

The issue with diffs can be solved by wrapping the ` || ` s in a span with a class called `tw-rollback-link-separator` or something. The code is in [rollbackLinks() function](https://github.com/wikimedia-gadgets/twinkle/blob/a449c8afe3c5a21d832bc860d5f9247e33298d93/modules/twinklefluff.js#L93) if you want to take a shot.

**Comment by ToBeFree** [comment]
Oh, thanks for the suggestion and the offer – I'll try! Thanks for locating the relevant code. Feel free to assign the issue to me.

**Comment by Xi-Plus** [comment]
> The issue with diffs can be solved by wrapping the `||` s in a span with a class called `tw-rollback-link-separator` or something.

I think using css ::before selector to show the separator is better.

**Comment by ToBeFree** [comment]
Thanks for the tip, I wasn't aware of that selection method. However, I disagree about such a workaround being "better" than proper classes for selection. There is currently no way to select even a specific link without resorting to :nth-child. MediaWiki shows nicely how to do it; I never had an issue finding a good CSS class selector, or at least an ID selector, when trying to customize elements. With the new code, selecting Twinkle's rollback links on any page with a single clean selector code finally becomes possible.

**Comment by Xi-Plus** [comment]
Adding class name is good for rollback links. I meant move separator node to the inside of links nodes. Just like MediaWiki:

![image](https://user-images.githubusercontent.com/7577245/115186931-17c36a80-a115-11eb-82ce-1c42dce8f135.png)

**Comment by ToBeFree** [comment]
Ah, that would indeed be very useful, thank you for the clarification – I'll adjust the code later! (Or anyone can do so if they like)

**Comment by ToBeFree** [comment]
done

**Comment by ToBeFree** [comment]
Semantic detail: "strong" was incorrectly used anyway. The "Revert to this revision" code correctly used bold font weight instead.
