### ISSUE TITLE
Extra colon in discussion page link 

### ISSUE THREAD

**Issue by siddharthvp** [wikimedia-gadgets/twinkle#1397]
https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&diff=1020864861
https://en.wikipedia.org/w/index.php?title=User_talk:Pakaran&diff=prev&oldid=1020864858

link to [[Wikipedia:Templates for discussion/Log/2021 May 1#:Template:POV]]. The colon before Template:POV prevents the link from working.

**Comment by NovemLinguae** [comment]
Appears to be an upstream error in https://en.wikipedia.org/wiki/Template:Tfm_notice . Twinkle correctly outputs `{{subst:Tfm notice|2=Unbalanced|1=Template:POV}}` with no colon. The template code looks complicated, I'll put in an edit request at https://en.wikipedia.org/wiki/Template_talk:Tfm_notice#Extra_colon

**Comment by NovemLinguae** [comment]
Fixed in the template, with thanks to Dinoguy1000
