### ISSUE TITLE
Remove welcome-graphical, welcome-menu, and welcome-screen, and add welcoming

### ISSUE THREAD

**Issue by sdkb** [wikimedia-gadgets/twinkle#1406]
Per the discussion at [Wikipedia talk:Twinkle#Welcome template options](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Welcome_template_options), I see a rough consensus to remove {{welcome-graphical}}, {{welcome-menu}}, and {{welcome-screen}} from the default welcome options, and to add [{{welcoming}}](https://en.wikipedia.org/wiki/Template:Welcoming). Could this be actioned?

For the description for {{welcoming}}, I'd suggest something like "welcome message with tutorial links and basic editing tips".

**Comment by fredster33** [comment]
+1.
