### ISSUE TITLE
Small bug with {{Summary2}}

### ISSUE THREAD

**Issue by sdkb** [wikimedia-gadgets/twinkle#1408]
When warning a user with [{{Summary2}}](https://en.wikipedia.org/wiki/Template:Uw-editsummary2), there's a box for putting in a linked article. The template does not support linking any specific article (nor do I think it should, since it's designed to warn about a broad behavioral pattern), so this should be removed.

**Comment by NovemLinguae** [comment]
Note: Need to add something to `Twinkle.warn.callback.change_subcategory` to show or hide the field.
