### ISSUE TITLE
Allow Extended Confirmed editors in addition to autoconfirmed

### ISSUE THREAD

**Issue by SamStrongTalks** [wikimedia-gadgets/twinkle#1414]
I'm working on doing a WP:FRESHSTART and a mop kindly transferred my permissions and such over, but I can't use Twinkle. It shows up in preferences to allow it to be turned on, but doesn't appear to load or show any UI. They didn't transfer autoconfirmed as I assume they assumed that Extended Confirmed would cover all of the use cases.

**Comment by ToBeFree** [comment]
@SamStrongTalks, you'd have needed the manual "confirmed" permission in addition to extended confirmation.

This is true for many edit filters, tools and other checks. The relevant Twinkle code is in the main twinkle.js, at the very beginning:

https://github.com/wikimedia-gadgets/twinkle/blob/a7d2e328ecd8d0d684d583a71f01325102385f2d/twinkle.js#L23

I assume you're autoconfirmed by now. If not: As there is now a public request about this, I do not recommend asking, even in private, for the manual confirmation bit to be added now. The resulting rights change would uniquely identify you.

@siddharthvp I recommend closing and deleting this bug report.

**Comment by siddharthvp** [comment]
Agree that this is a very rare edge case which is better solved by adding the `confirmed` group, like for other tools, edit filters, etc.
