### ISSUE TITLE
Add Template:R from non-neutral name

### ISSUE THREAD

**Issue by sdkb** [wikimedia-gadgets/twinkle#1415]
Could we add [{{Template:R from non-neutral name}}](https://en.wikipedia.org/wiki/Template:R_from_non-neutral_name) to the supported redirect tags?

**Comment by NovemLinguae** [comment]
@sdkb I'll code this one, if you tell me what category to put it in. Can you go to a random redirect page, click tag, look at the categories, and let me know which one {{R from non-neutral name}} would best fit in to? Thanks.

**Comment by sdkb** [comment]
Hi NovemLinguae; thanks! I think Alternative Names > General would be best.
