### ISSUE TITLE
Wikipedia:TWA/InviteTW isn't properly substituted

### ISSUE THREAD

**Issue by ToBeFree** [wikimedia-gadgets/twinkle#1419]
Wikipedia:TWA/InviteTW is transcluded, not substituted, by Twinkle. This results in an "edit section" link pointing to the template itself, and has already caused multiple users to edit the template instead of the user's talk page.

**Comment by siddharthvp** [comment]
@ToBeFree What module of Twinkle are we talking about? I don't see "Wikipedia:TWA/InviteTW" in a directory-wide search of Twinkle source code.
