### ISSUE TITLE
Remove book PROD

### ISSUE THREAD

**Issue by siddharthvp** [wikimedia-gadgets/twinkle#1421]
Book namespace has been deprecated (https://en.wikipedia.org/wiki/Wikipedia:Village_pump_(proposals)#The_future_of_the_Book_namespace) and all books in the namespace are going to be deleted (https://en.wikipedia.org/wiki/Wikipedia:Village_pump_(proposals)#Delete_all_books_within_the_book_namespace).

Though userspace books are still a thing, WP:BOOKPROD has been marked historical per a very brief discussion at https://en.wikipedia.org/wiki/Wikipedia_talk:Proposed_deletion_(books)#Mark_process_as_historical. We should probably wait for a bit to see if that's going to be challenged. Anyway, even if userspace bookprod is going to remain in policy (unlikely), I think we can still remove it from Twinkle given the lack of use.

Back in the day, adding support for book prod (#457) was my first non-trivial contribution to Twinkle!

**Comment by Trialpears** [comment]
I'm aware of this and can remove it this weekend if no one gets to it first. I feel like it would be safe to remove the feature at the same time the templates are deleted.

**Comment by siddharthvp** [comment]
@Trialpears There was a bug in the PROD module because of which its window wouldn't even open. That was due to a bug in the unreleased version that's now fixed in 7bca342. Do you still plan to work on this?
