### ISSUE TITLE
Read delsort topics from wiki page

### ISSUE THREAD

**Issue by siddharthvp** [wikimedia-gadgets/twinkle#1428]
[Wikipedia:WikiProject Deletion sorting/Computer-readable.json](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Deletion_sorting/Computer-readable.json) was recently created and is being used by User:Enterprisey/delsort.js. Twinkle also should read delsort topics from there to avoid having to make source code changes whenever delsort pages have to be added/removed. 

The JSON page should be read via the API only when needed (i.e, when user opens the XFD module) and cached for a suitable period (say 1 day), using the API's maxage/smaxage parameters.

**Comment by NovemLinguae** [comment]
I'll probably code this one soon. Design notes:

- will probably check json file on local wiki, not just hard-coded to enwiki
- would be a good idea to validate the data a bit, for example, making sure it is in fact a two level object
- will need to handle empty object and undefined object gracefully

**Comment by NovemLinguae** [comment]
I'm stuck on async issues. How do I fill up the wikitext variable here with wikitext? Do I have to wrap everything after this code block in a callback? This is all in a big break statement with even more code after the break, so that would get messy.

I could hack it in with `$.ajax({async:false});` but I assume there's a better way.

Any hints appreciated.

````
			// delsort categories taken from [[Wikipedia:WikiProject Deletion sorting/Computer-readable.json]]
			var query = {
				action: 'parse',
				page: 'Wikipedia:WikiProject_Deletion_sorting/Computer-readable.json',
				prop: 'text',
				formatversion: '2'
			};
			var wikitext = '';
			var api = new Morebits.wiki.api('Get JSON list of deletion sorting categories', query, function(apiobj) {
				wikitext = apiobj.getResponse().parse.text;
			});
			api.post();

**Comment by siddharthvp** [comment]
The key is to _not_ wait for the API call before rendering the form. The `<select>` can be empty to begin with. Just trigger the API – whenever it resolves, add the `<option>`s to the `<select>` which would be present on the page by this time.
