### ISSUE TITLE
twinkleprotect: <noinclude> deletion discussions by default

### ISSUE THREAD

**Issue by ToBeFree** [wikimedia-gadgets/twinkle#1432]
Deletion discussions are always transcluded. Hence, the following should be the default on pages in the Wikipedia namespace prefixed by "Articles_for_deletion/":

https://en.wikipedia.org/w/index.php?title=Wikipedia:Articles_for_deletion/Wehda_Street_massacre&diff=1035970865&oldid=1035970295&diffmode=source

**Comment by Dreamy-Jazz** [comment]
I've created a pull request for that feature.
