### ISSUE TITLE
Add the option of type=disabled to TfD

### ISSUE THREAD

**Issue by Gonzom** [wikimedia-gadgets/twinkle#1445]
Add the option of type=disabled to TfD which is supported by the template, see [Template:Template for discussion#Disabled.](https://en.wikipedia.org/wiki/Template:Template_for_discussion#Disabled)

**Comment by NovemLinguae** [comment]
Any preference for whether `{{TFD|type=disabled}}` should add an enter character after itself or not? I wrote code that adds an enter, but I can make it "inline" (no enter) if desired.
