### ISSUE TITLE
MI grouping failure

### ISSUE THREAD

**Issue by siddharthvp** [wikimedia-gadgets/twinkle#1449]
https://en.wikipedia.org/wiki/Special:Diff/1046045935

(Reported at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Twinkle_did_not_group_tags)

**Comment by NovemLinguae** [comment]
Unable to reproduce. `{{Only primary sources}}` is not a tag currently in Twinkle. I also do not see "only primary sources" when searching all files for that string.

cc @1234qwer1234qwer4 if you're on GitHub

Suggest closing.

**Comment by siddharthvp** [comment]
Oh, got it - {{Only primary sources}} is a custom tag from [User:1234qwer1234qwer4/twinkleoptions.js](https://en.wikipedia.org/wiki/User:1234qwer1234qwer4/twinkleoptions.js). Since Twinkle doesn't know whether custom tags are groupable, it doesn't put them in MI. So, not a bug indeed.

**Comment by NovemLinguae** [comment]
I didn't know Twinkle supported adding your own maintenance tags. Anyway now that I know that, I think it'd be reasonable for Twinkle to assume that all maintenance tags (including custom ones) support grouping in {{MI}}. If you want, I think we can re-open this and tag it "needs code".

Under the hood, any maintenance tag that uses {{Ambox}} supports being placed in {{MI}}.

**Comment by siddharthvp** [comment]
There are quite a few which are not supported - indicated with `excludeMI: true` in the [code](https://github.com/wikimedia-gadgets/twinkle/blob/master/modules/friendlytag.js). For custom tags since we aren't sure, I think the original intention was to err on the side of not leaving behind malformed templates on the page.
