### ISSUE TITLE
Fix redirect category namespace detection

### ISSUE THREAD

**Issue by sdkb** [wikimedia-gadgets/twinkle#1459]
Twinkle recently let me categorize a template redirect page with {{t|R from other capitalisation}}. It was only after saving that I noticed the warning that that template shouldn't be used outside of mainspace, and the documentation states that {{t|R from modification}} should be used in those circumstances instead. Could the Twinkle menu options please be adjusted so that only tags that belong on a page in a given namespace are offered?

**Comment by NovemLinguae** [comment]
{{doing}}. Are there any other rules that should be added besides this "no {{R from other capitalization}} in template namespace" rule?

**Comment by sdkb** [comment]
Thanks! I haven't personally encountered any besides this one (which applies to anywhere outside mainspace, not just template space), but I imagine that if one looked through the category of redirect tags thoroughly there would probably be others.

**Comment by NovemLinguae** [comment]
{{done}}, will submit PR in a moment. After investigating, I found around 180 tags that are namespace-specific, and I coded them all in.
