### ISSUE TITLE
Read discretionary sanctions information from a wiki page

### ISSUE THREAD

**Issue by siddharthvp** [wikimedia-gadgets/twinkle#1477]
`Twinkle.block.dsinfo` added in #1039 is currently hard-coded which necessitates Twinkle maintainers to update add/remove DS sanctions as and when updated by ArbCom. I wonder if it isn't already outdated. This could instead be read from a JSON page on-wiki so that Twinkle maintainers don't have to follow Arbcom proceedings. Then it could even be updated by ArbCom clerks. 

As for implementation, the JSON fetch logic used for delsort could be abstracted out into morebits.js or twinkle.js files, and reused here.

**Comment by siddharthvp** [comment]
Note regarding testing changes for admin modules: Best way is to have +sysop on the testwiki. Otherwise, you can get Twinkle to behave as if you're an admin by running `Morebits.userIsSysop = true`. For summoning the block module window, run `Twinkle.block.callback()` which should work regardless of the Morebits.userIsSysop value.

**Comment by NovemLinguae** [comment]
Twinkle block module is acting kind of buggy on my localhost wiki. Any hints?

![image](https://user-images.githubusercontent.com/79697282/143765290-049537af-eb50-4ca4-a4fa-ba87e644d38a.png)

**Comment by siddharthvp** [comment]
One of the issues is that the select2 library is missing. You can register it as a gadget there, the way we've done it on enwiki & testwiki. (See [the gadget definition](https://en.wikipedia.org/wiki/MediaWiki:Gadgets-definition), [js](https://en.wikipedia.org/wiki/MediaWiki:Gadget-select2.min.js), [css](https://en.wikipedia.org/wiki/MediaWiki:Gadget-select2.min.css)). 

Not sure why template options is empty, though. There should be some error in the console.
