### ISSUE TITLE
speedy: add {{Db-afc-move}}

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1510]
New template that @Primefac created. This issue is a note to self to add it if there's consensus, once it stabilizes, etc.

**Comment by siddharthvp** [comment]
I think it's better to integrate this template into AFCH. If available in twinkle, it should probably be restricted to AFC reviewers, but then it isn't easy for twinkle to determine if the user is an AFC reviewer.

**Comment by primefac** [comment]
I don't disagree, it's a good idea to chuck it into AFCH, but I fail to see the usefulness - AFCH is for accepting - if you're going to accept, why "accept" it twice (once to place the db- tag, once to move it)? I guess I'm just not seeing the workflow.

**Comment by siddharthvp** [comment]
If the user is not an admin, AFCH could offer an option to {{db-afc-move}}-tag the target page since actually accepting is not possible.

**Comment by NovemLinguae** [comment]
Tried to use {{Db-afc-move}} today. It's not in Twinkle or AFCH yet. First I forgot what the template name was so I had to spend a few minutes finding it. Then I forgot to put the required |page= parameter.

Putting this in Twinkle would be an efficiency for this workflow.
