### ISSUE TITLE
speedy: Support G6 (db-moved)

### ISSUE THREAD

**Issue by fredster33** [wikimedia-gadgets/twinkle#1539]
https://en.wikipedia.org/wiki/Template:Db-moved

**Comment by NovemLinguae** [comment]
Template:Db-moved appears to be a custom version of Template:Db-move, with emphasis on those who have the page mover right.

Seems fine to add.

**Comment by Trialpearswiki** [comment]
Honestly I don't think this is a great addition. I was a page mover for some time before becoming an admin and in that time I never felt like I was missing this template. Either I made a round robin move or placed the page that was in the way as a new redirect  at an appropriate title. While there is a use case I believe it to be very rare. 

Normally that wouldn't be quite enough for me to oppose addition, but given that confusion with db-move is highly likely I don't think the benefit of slightly clearer tagging in a small number of cases outweighs the likely significant confusion when tagging for db-move cases.

**Comment by NovemLinguae** [comment]
Fair enough. Now that there's objection, will go ahead and close this. If someone wants to resume discussion about it here or at WT:TWINKLE, feel free.
