### ISSUE TITLE
protect: rename {{pp-30-500}} to {{pp-extended}}

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1542]
https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Page_protection_template_pp-30-500

![2022-03-17_082641](https://user-images.githubusercontent.com/79697282/158834174-7f55ffc9-15b3-4e07-816f-258d38a80bac.png)

Might want to refactor some other spots too:

![image](https://user-images.githubusercontent.com/79697282/158835957-2a590481-9352-4ae7-adac-8b20c71fa6fc.png)

**Comment by codesmith25103** [comment]
Sir, I want to work on this issue. Please assign me this

**Comment by codesmith25103** [comment]
Sir, I had clone the git repository and run the command "npm install".  But i am not getting what to do next. Can you please guide me. I am new to open source.

**Comment by NovemLinguae** [comment]
Assuming the `npm install` went smoothly, next do `npm start`, then add `mw.loader.load('http://127.0.0.1:5500')` to your User:yourUserName/common.js file on https://test.wikipedia.org/. Then make your code changes and test them out. Detailed directions at https://github.com/wikimedia-gadgets/twinkle/blob/master/CONTRIBUTING.md#getting-started
