### ISSUE TITLE
Add option: {{Convert to STL}} for file description page

### ISSUE THREAD

**Issue by c933103** [wikimedia-gadgets/twinkle#1545]
The template https://commons.wikimedia.org/wiki/Template:Convert_to_STL help tag files that can be converted into 3D model format for uploading onto Wikimedia Commons, like Convert to PNG or Convert to SVG template. I think it would be a good idea for users to be able to easily tag a file with this template for conversion to 3D model via Twinkle.

**Comment by NovemLinguae** [comment]
I think this is the repo for enwiki's Twinkle. According to [this](https://commons.wikimedia.org/wiki/Commons:Twinkle), regular Twinkle does not work on commons. What Twinkle do you have installed in your common.js?

**Comment by c933103** [comment]
Ah, I didn't realize it. I just saw the Twinkle option in English Wikipedia for file page have {{Should be PNG}} and
{{Should be SVG}} options, then think it would be a good idea for twinkle on commons to have something like this.
