### ISSUE TITLE
Twinkle has stopped creating FfD subsections

### ISSUE THREAD

**Issue by ixfd64** [wikimedia-gadgets/twinkle#1565]
I noticed that Twinkle has stopped creating subsections for files that are nominated on FfD.

Steps to reproduce:

1. Nominate a file on Files for Discussion

Expected results:

1. Twinkle adds an FfD notice to the file
2. A subsection for the file is created on FfD
3. Uploader is notified

Actual results:

1. The subsection is not created. Twinkle gets stuck at "Retrieving page..."

![xfd_issue](https://user-images.githubusercontent.com/1526759/163253244-f5efbb39-d191-4457-8e20-b17f8416e001.png)

This just started happening for me today. It is pretty strange because there have been no recent code changes.

**Comment by NovemLinguae** [comment]
We deployed an update today. Could be related. Thanks for reporting, I'll investigate.

**Comment by NovemLinguae** [comment]
Related #1524

There's a bug in this code. I'll deploy a patch shortly.

**Comment by NovemLinguae** [comment]
Hotfixed on wiki. Should be fixed when the gadget cache clears. Please let me know if you find any other issues.

**Comment by ixfd64** [comment]
The issue seems to be fixed. Thank you!
