### ISSUE TITLE
API error notice: Unrecognized value for parameter "letype": stable

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1596]
Steps to reproduce:

- Open DevTools -> Network tab. Filter by Fetch/XHR
- Template protect an unprotected template
- Hit F8 twice after all actions completed but before the page reloads. This will pause JavaScript execution, allowing you to examine the network traffic without the page reloading.
- Find the appropriate` api.php?action=query&format=json&list=logevents&letype=stable` entry by checking the Preview tab for `{error: {code: "badvalue", info: "Unrecognized value for parameter "letype": stable`

![2022-06-09_124134](https://user-images.githubusercontent.com/79697282/172931072-e189b37f-edf7-4ac3-9b34-da2c1ce2141a.png)

![2022-06-09_124122](https://user-images.githubusercontent.com/79697282/172931082-619e8102-6174-4549-b221-c573b9f11d61.png)

![2022-06-09_124105](https://user-images.githubusercontent.com/79697282/172931097-9478b819-ad91-4eee-be4c-d53632ef488d.png)

https://www.mediawiki.org/wiki/API:Logevents

![image](https://user-images.githubusercontent.com/79697282/172932572-b5f106b5-a06e-4c05-bca5-7d62d698eac9.png)

**Comment by siddharthvp** [comment]
Note that letype=stable is added by [Extension:FlaggedRevs](https://www.mediawiki.org/wiki/Extension:FlaggedRevs), which is not installed on either testwiki or mediawikiwiki. This should be working alright on enwiki.

See the dynamically generated API docs on enwiki domain:

<img width="1183" alt="Screenshot 2022-06-13 at 12 04 37 PM" src="https://user-images.githubusercontent.com/31818903/173293608-604bcf72-f0b7-4ce2-a22d-efcc9c206734.png">

**Comment by NovemLinguae** [comment]
Thanks for pointing this out. I will see if there is consensus to get FlaggedRevs installed on testwiki. Closing since this is not a bug after all.

https://test.wikipedia.org/wiki/Wikipedia:Village_pump#Additional_testwiki_user_rights_to_sync_up_with_enwiki
