### ISSUE TITLE
malformed headers

### ISSUE THREAD

**Issue by shakil-mdshosen** [wikimedia-gadgets/twinkle#1625]
Twinkle add extra markup in the headers when posting warnings, which results in malformed headers. Examples: [1](https://en.wikipedia.org/w/index.php?title=User_talk:Diannaa&diff=1101007133&oldid=1101000239) [2](https://en.wikipedia.org/w/index.php?title=User_talk:Ninja_Diannaa&diff=1101006677&oldid=1100093878)  bnwiki: [1](https://w.wiki/5Wjg)  [2](https://bn.wikipedia.org/wiki/%E0%A6%AC%E0%A6%BF%E0%A6%B6%E0%A7%87%E0%A6%B7:%E0%A6%AA%E0%A6%BE%E0%A6%B0%E0%A7%8D%E0%A6%A5%E0%A6%95%E0%A7%8D%E0%A6%AF/6006925)

**Comment by Xi-Plus** [comment]
It's due to a unexpected API changes: https://gerrit.wikimedia.org/r/c/mediawiki/core/+/814003/4/includes/EditPage.php#b1151
The API stop striping `==` syntax.
