### ISSUE TITLE
Usernames with quotes in them are incorrectly escaped in {{SPIarchive notice}}

### ISSUE THREAD

**Issue by roysmith** [wikimedia-gadgets/twinkle#1665]
Look at https://en.wikipedia.org/w/index.php?title=Wikipedia:Sockpuppet_investigations/%22Ghgfhc%22&oldid=1120996497

The CheckUser link for "Ghgfhc" doesn't work right.  Looking at the wiki source, you generate:

`{{SPIarchive notice|&#34;Ghgfhc&#34;}}`

I'm pretty sure that should be:

`{{SPIarchive notice|"Ghgfhc"}`

like it is in the {{sock list}} template further down.

**Comment by NovemLinguae** [comment]
@roysmith. Thanks for the bug report. I was able to reproduce, but it appears to be a template error. The code that Twinkle generates is something like...

```
{{subst:SPI report|1="Hasojerna"
|evidence=Both have username in quotes. Both are SPAs with the same purpose, namely to target [[National Socialism (disambiguation)]] with incoherent nonsense heavily featuring the word "intellectual" (and variants). I think this is an attempt to push a POV but it is too incoherent to say exactly what that POV is. "Ghgfhc" got reverted and got warned, then "Hasojerna" popped up to continue in the same vein. The style is so similar that there is almost no chance that it is two different people. [[User:DanielRigal|DanielRigal]] ([[User talk:DanielRigal|talk]]) 23:41, 9 November 2022 (UTC) 
|checkuser=yes}}
```

As you can see, the sockmaster's name isn't even included in this template, so there's no way that Twinkle could be the cause of the problem. Instead, {{SPI report}} or one of its sub-templates such as {{SPI report/header}} or {{SPI archive notice}} must be grabbing the incorrectly escaped name. My money is on {{SPI archive notice}}

https://en.wikipedia.org/w/index.php?title=Template:SPI_archive_notice&action=edit

Perhaps something related to [MediaWiki magic words](https://www.mediawiki.org/wiki/Help:Magic_words) such as {{SUBPAGENAME}}

Hope that helps.

**Comment by NovemLinguae** [comment]
Looks like the issue was fixed with this diff: https://en.wikipedia.org/w/index.php?title=Template:SPI_report/header&diff=1121276664&oldid=1069693990&diffmode=source
