### ISSUE TITLE
Twinklewarn: Add Template:uw-refspam as a single-issue notice

### ISSUE THREAD

**Issue by ToBeFree** [wikimedia-gadgets/twinkle#1666]
https://en.wikipedia.org/wiki/Template:Uw-refspam describes an issue probably common enough to justify inclusion in the list of single-issue notices.

**Comment by Habibi-Panda** [comment]
hey can you tell me some detail about this issue maybe i can solve it.

**Comment by NovemLinguae** [comment]
@Habibi-Panda. You can add this around modules/twinklewarn.js line 923, then submit a pull request. Don't forget to test it on https://test.wikipedia.org/. Details on how to test located at https://github.com/wikimedia-gadgets/twinkle/blob/master/CONTRIBUTING.md#testing-your-code

**Comment by Monik2002** [comment]
done
