### ISSUE TITLE
Vector 2022: Twinkle menu does not appear on hover

### ISSUE THREAD

**Issue by jonesey95** [wikimedia-gadgets/twinkle#1674]
My apologies if this is a duplicate bug. I looked through the list but did not see this issue.

See https://phabricator.wikimedia.org/T325037 for details. There are two bugs here, possibly related:

1. The TW menu does not drop down when hovering the mouse over the menu. It works fine in Vector (legacy).

~~2. Click on the Twinkle (TW) menu, then Click on the More menu (the one with Move in it). The TW menu does not disappear when you click the More menu.~~ split into #1675

**Comment by jonesey95** [comment]
Note: A helpful editor at the en.WP Village Pump gave me this code for my common.css, which works. If it makes sense to integrate it into the Twinkle menu, here it is:
`.vector-menu-checkbox:hover ~ .vector-menu-content, .vector-menu-content:hover {
	opacity: 1;
	visibility: visible;
	height: auto;
}`

**Comment by NovemLinguae** [comment]
# 1 is reproducible in vector 2022

# 2 is reproducible in vector 2022 and vector 2010

**Comment by NovemLinguae** [comment]
I went ahead and split this into 2 bugs. See #1675

**Comment by codesmith25103** [comment]
I want to work on this issue.. can you assign me?

**Comment by nardog** [comment]
#1676 should cover it. (@NovemLinguae what's the difference between this and 1676?)

**Comment by NovemLinguae** [comment]
> #1676 should cover it. (@NovemLinguae what's the difference between this and 1676?)

@nardog This is the bug report (similar to Phabricator), and #1676 is the PR (similar to Gerrit).

**Comment by NovemLinguae** [comment]
> I want to work on this issue.. can you assign me?

@codesmith25103 , I already wrote a patch for this issue at #1676. However you are welcome to work on any other open issues without pull requests attached ([list here](https://github.com/wikimedia-gadgets/twinkle/issues)). And also [here's a list of issues tagged with "good first task"](https://github.com/wikimedia-gadgets/twinkle/labels/good%20first%20task), which should be easy to code.
