### ISSUE TITLE
Vector and vector 2022: Twinkle menu does not go away when clicking/hovering the More menu

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1675]
Related #1674. Reported by @jonesey95

Steps to reproduce
* ?useskin=vector or ?useskin=vector-2022
* click on "TW" menu to open it. leave it open
* hover over or click on "more" menu to open it

Actual behavior
* TW menu stays open

Expected behavior
* TW menu closes

**Comment by jonesey95** [comment]
See https://en.wikipedia.org/wiki/User:Jonesey95/common.css for code that appears to fix this.

**Comment by nardog** [comment]
That's a fix for #1675, which is slightly different.

**Comment by siddharthvp** [comment]
It is the intended behaviour. All buttons are independent of each other. Clicking on the "more" menu and then on TW menu doesn't hide the more dropdown. If you have MoreMenu installed, its "Page" and "User" buttons also behave the same way.

**Comment by jonesey95** [comment]
There are no menus that work like this in any common UI. Menus on the same menu bar are exclusive of one another.

**Comment by NovemLinguae** [comment]
Fair enough. I'll close this one then. Thanks for the feedback.
