### ISSUE TITLE
license is missing

### ISSUE THREAD

**Issue by jindam-vani** [wikimedia-gadgets/twinkle#1690]
hello twinkle devs, there seems to be no project 
license, can you please update [OSI approved](https://wikitech.wikimedia.org/wiki/Help:Toolforge/Rules)

* it has come to my attention about [tool sweep](https://lists.wikimedia.org/hyperkitty/list/cloud@lists.wikimedia.org/thread/4MAN77NS47TRANE3DK375VL3W3XGY4CT/) on cloud mailing list

**Comment by NovemLinguae** [comment]
We're not on Toolforge, so I don't think this is required for us.

However, wouldn't hurt to do it. Do we just add a LICENSE.md file to the root with a copy paste of Creative Commons Attribution-ShareAlike License 3.0?

**Comment by jindam-vani** [comment]
@NovemLinguae thankd for quick reply. #252 was also about absence of license on repo. perhaps time has come to remind and update about choosing an osi complaint license for any software used for wikimedia projects
