### ISSUE TITLE
Move .toccolours CSS into Twinkle

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1704]
Requested by Izno at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#toccolours_removed_in_Vector_22

.toccolours is used by Twinkle to style something in morebits.js

.toccolours works in vector but not vector-2022

The CSS for it should probably be copied into Twinkle and named .morebits-toccolours or something. Similar to what I did in a previous patch.

**Comment by siddharthvp** [comment]
It's used to style the Twinkle-generated content in case it could not saved to the page due to an error:

Run:
```js
Twinkle.speedy.callback();
Morebits.status.init($(".quickform")[0]);
Morebits.status.printUserText('{{User text}}', 'shown below is your text');
```
The user text appears unstyled in vector-2022.

Looks like all the required CSS is:
```css
border: 1px solid #a2a9b1;
background-color: #f8f9fa;
padding: 5px;
font-size: 95%;
```
