### ISSUE TITLE
speedy: remove F10

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1719]
Requested by Extraordinary Writ at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#F10_is_no_more

Remove CSD F10

Per RFC result

**Comment by siddharthvp** [comment]
@Trialpearswiki you can write "Closes #1719" or "Fixes #1719" in the PR description or commit message so that the issue gets auto-closed when the PR is merged.
