### ISSUE TITLE
friendlytag: response.pagetriagelist.pages[0] is undefined

### ISSUE THREAD

**Issue by nardog** [wikimedia-gadgets/twinkle#1737]
Steps:
- Open https://en.wikipedia.org/wiki/Cambuquira
- Select "Tag"

Line: [friendlytag.js:56](https://github.com/wikimedia-gadgets/twinkle/blob/0654f8c1beefaefd807e6a045fdd3315c854afdb/modules/friendlytag.js#L56)

XHR response:
```json
{
    "pagetriagelist": {
        "result": "warning",
        "pages_missing_metadata": [
            8657842
        ],
        "pages": []
    }
}
```

**Comment by NovemLinguae** [comment]
Caused by my patch 2926bef7a5950d5722dedac58156a741c30245a8

Fix should be pretty easy. Will try to get to it soon. Thanks for catching this.
