### ISSUE TITLE
welcome: add {{Welcome-copyright}}

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1757]
Requested by Red-tailed hawk at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Please_add_%7B%7BWelcome-copyright%7D%7D_to_Twinkle

Add it to the "problem user" section of the welcome module

<img width="696" alt="image" src="https://user-images.githubusercontent.com/79697282/224503846-e213e107-1a04-4c28-82e4-3afba3fcf217.png">

**Comment by Red-tailed-Hawk** [comment]
I might take a look today at implementing this. Not super familiar with the Twinkle codebase at the moment, but it would be a good first task.

**Comment by NovemLinguae** [comment]
Would just need to modify some json, then test it, then submit a pull request. The contributing.md file has instructions on how to test.

**Comment by Red-tailed-Hawk** [comment]
I've submitted a pull request related to this.
