### ISSUE TITLE
fluff: warn window doesn't pop up sometimes after clicking [vandalism]

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1764]
Reported by Matt Deres at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Unable_to_place_warnings

Possibly intermittent. Seemed to be working for me at one point, but then was reproducible for me later.

Reproduced on both vector and monobook

Steps to reproduce
- use account 1 to make an edit
- use account 2 to open a diff page
- use account 2 to click [vandalism], which will rollback the edit and then pop up a new browser window with the bookmarks bar hidden containing the user talk page in "edit and preview" mode, and no changes in text yet

What should have happened?
- warn module pops up, with vandalized page title pre-filled

What happens instead?
- warn module does not pop up
- no javascript console errors
- occurs for multiple kinds of diffs (including diffs from "history" page, and diffs from "recent changes" page, whose URLs have slightly different parameters)

![image](https://user-images.githubusercontent.com/79697282/227799182-482f9940-564f-412b-bfb1-0f28ad04e2ee.png)

![image](https://user-images.githubusercontent.com/79697282/227799258-47cab42f-e562-48b4-978c-9aa82910520c.png)

**Comment by NovemLinguae** [comment]
cc @nardog in case one of [your recent patches](https://github.com/wikimedia-gadgets/twinkle/commit/30ec330be93e84dffebc286484094bc8e66421cb) might be involved. And because you probably know the fluff module better than me since you've been working on it lately :)

**Comment by nardog** [comment]
If anything is wrong with a module it's warn, not fluff, as warn is what opens the dialog. If "Automatically open the Twinkle warn menu on a user talk page after Twinkle rollback" is off, which it is by default, the warn dialog should never open automatically, period. I don't think you and Matt Deres are describing the same problem.

**Comment by NovemLinguae** [comment]
I think I got confused. Thanks for setting me straight Nardog. Closing this ticket. Will open a different ticket if troubleshooting efforts at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Unable_to_place_warnings don't fix the problem.
