### ISSUE TITLE
Add {{WikiProject Women in Red invite}} to custom welcomes

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1776]
Requested by asilvering at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Wikiproject_welcome_addition

**Comment by Monik2002** [comment]
I want to work on this issue

**Comment by NovemLinguae** [comment]
Sure go ahead. We don't really assign tasks around here. Just submit a PR when ready.

**Comment by NovemLinguae** [comment]
Actually never mind, someone already submitted a PR for this one at #1792. Better pick a different issue.

**Comment by Monik2002** [comment]
so the issue should be closed . Right ?

**Comment by NovemLinguae** [comment]
It will auto close when I approve the existing pull request.
