### ISSUE TITLE
Unit test CI may be broken

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1778]
I don't see the unit test continuous integration (`.github/workflows/unit_test.yml`) running on most pull requests. Of the couple of pull requests I sampled, it was only running for dependabot pull requests.

Is there some reason that the tests would only run for certain patches and not others?

A bunch of tests are also failing on localhost, which may complicate fixing this.

**Comment by siddharthvp** [comment]
It only runs if morebits.js or the tests themselves were edited, as the unit tests used to cover only morebits.
