### ISSUE TITLE
Various image templates were renamed

### ISSUE THREAD

**Issue by pppery** [wikimedia-gadgets/twinkle#1788]
i.e {{Di-orphaned fair use}} -> {{Di-orphaned non-free use}}, {{Di-disputed fair use rationale}} -> {{Di-disputed non-free use rationale}}

Twinkle should be updated to use the new name instead of the redirect.

**Comment by Monik2002** [comment]
<img width="491" alt="image" src="https://github.com/wikimedia-gadgets/twinkle/assets/87751450/11b72d0d-bfaf-4be0-9114-f51457573d9d">

So , I just need to update the line from orphaned fair use to orphaned non-free use ?

**Comment by NovemLinguae** [comment]
Looks like the correct approach. May also want to double check on enwiki that each new template name exists and also that it isn't a redirect. (A redirect would indicate that you can just rename it to whatever it is redirecting to.)
