### ISSUE TITLE
support for bundled AFDs

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1813]
support for bundled AFDs. WP:BUNDLE. https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion#How_to_nominate_multiple_related_pages_for_deletion

I don't think there's any user scripts/gadgets that do this yet. And the manual process can be error-prone and require AWB runs to place all the {{Articles for deletion/dated}} templates. Might be worth allowing up to 10 AFDs or something as a trial run, and if that goes well, increase the limit.

examples:
* https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/Allen_Shop_Corner,_Virginia
* https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/Ross_MacDonald
* https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/Anibal_Ramos_Jr.
* https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/Dmitriy_Grigoriyev_(2nd_nomination)
* https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/Lawthorne_Mill,_Virginia
* https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/List_of_Muslim_Nobel_Laureates
* https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/Ernie_Toshack_with_the_Australian_cricket_team_in_England_in_1948
* more search results at https://en.wikipedia.org/w/index.php?search=bundle+-intitle%3Abundle+subpageof%3A%22Articles+for+deletion%22&title=Special:Search&profile=advanced&fulltext=1&advancedSearch-current=%7B%22fields%22%3A%7B%22subpageof%22%3A%22Articles+for+deletion%22%7D%7D&ns0=1&ns1=1&ns2=1&ns3=1&ns4=1&ns5=1&ns6=1&ns7=1&ns8=1&ns9=1&ns10=1&ns11=1&ns12=1&ns13=1&ns14=1&ns15=1&ns100=1&ns101=1&ns118=1&ns119=1&ns710=1&ns711=1&ns828=1&ns829=1&ns2300=1&ns2301=1&ns2302=1&ns2303=1

**Comment by siddharthvp** [comment]
See #421

**Comment by NovemLinguae** [comment]
Duplicate. Merging.
