### ISSUE TITLE
tag: Add {{No significant coverage (sports)}}

### ISSUE THREAD

**Issue by earlt612** [wikimedia-gadgets/twinkle#1817]
I noticed that this template was missing from Twinkle, thus this issue.

**Comment by NovemLinguae** [comment]
We should wait and see how the [TFD](https://en.wikipedia.org/wiki/Wikipedia:Templates_for_discussion/Log/2024_September_4#Template:No_significant_coverage_(sports)) goes. even if the TFD passes, maybe we should decline to add this one. I might need to think about it.
