### ISSUE TITLE
linter: add rules for spaces inside parentheses

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1827]
linter: add rules for spaces inside parentheses

MediaWiki style. Slightly less brainpower for MediaWiki devs to just write in their normal style.

Current style:
`if (namespace === 2 || namespace === 3) {`

New style
`if ( namespace === 2 || namespace === 3 ) {`

* [ ] add lint rule
* [ ] run --fix to update current code

**Comment by nardog** [comment]
-1, this makes the code less legible with little to no gain, especially if you use an editor capable of highlighting corresponding brackets.

**Comment by siddharthvp** [comment]
Agreed with @nardog on this. Not putting spaces in parentheses is the more common style (eg. see the [Google style guide](https://google.github.io/styleguide/jsguide.html)). It is MediaWiki which deviates from the standard here.
