### ISSUE TITLE
twinkle: switch to mw.util.addPortlet() function

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1835]
When `mw.util.addPortlet()` is finished and deployed, replace a lot of our `Twinkle.addPortlet()` code with the new `mw.util.addPortlet()`.

This will pay off some technical debt and make Twinkle less likely to break when changes are made to Vector 2022.

https://phabricator.wikimedia.org/T303488

## Skins we need to support

Twinkle has special cases in the code for vector-2022, vector, modern, and timeless. Twinkle probably also needs to support monobook. Twinkle does not need to support Minerva (there is a different Twinkle for mobile users).

## Existing bugs in the `Twinkle.addPortlet()` code

Twinkle's current `Twinkle.addPortlet()` code is not perfect. For example, the portlet code generated for Timeless doesn't match other nearby portlet code, suggesting we are using the wrong HTML here.

<img width="581" alt="image" src="https://github.com/wikimedia-gadgets/twinkle/assets/79697282/dbf22e68-f5b2-4df6-a792-7bb38f085f15">

## Complexity

The `Twinkle.addPortlet()` code at first glance looks like it lets the user adjust a bunch of settings, because it takes 5 parameters, and the parameters come from `getPref()`...

```js
/**
 * @param {String} navigation id of the target navigation area (skin dependant, on vector either of "left-navigation", "right-navigation", or "mw-panel")
 * @param {String} id id of the portlet menu to create, preferably start with "p-".
 * @param {String} text name of the portlet menu to create. Visibility depends on the class used.
 * @param {String} type type of portlet. Currently only used for the vector non-sidebar portlets, pass "menu" to make this portlet a drop down menu.
 * @param {Node} nextnodeid the id of the node before which the new item should be added, should be another item in the same list, or undefined to place it at the end.
 */
Twinkle.addPortlet(
    Twinkle.getPref('portletArea'),
    Twinkle.getPref('portletId'),
    Twinkle.getPref('portletName'),
    Twinkle.getPref('portletType'),
    Twinkle.getPref('portletNext')
);
```

But in reality these are hard-coded in twinkle.js. I don't see the word "portlet" or "skin" anywhere on the [Twinkle preferences page](https://en.wikipedia.org/wiki/Wikipedia:Twinkle/Preferences).

A refactor should probably move these hard-coded preferences into the `Twinkle.addPortlet()` function itself, and get rid of all the incoming parameters. In my opinion, there should only be one incoming parameter (`skin`).

```js
// now some skin dependent config.
switch (mw.config.get('skin')) {
	case 'vector':
	case 'vector-2022':
		Twinkle.defaultConfig.portletArea = 'right-navigation';
		Twinkle.defaultConfig.portletId = 'p-twinkle';
		Twinkle.defaultConfig.portletName = 'TW';
		Twinkle.defaultConfig.portletType = 'menu';
		Twinkle.defaultConfig.portletNext = 'p-search';
		break;
	case 'timeless':
		Twinkle.defaultConfig.portletArea = '#page-tools .sidebar-inner';
		Twinkle.defaultConfig.portletId = 'p-twinkle';
		Twinkle.defaultConfig.portletName = 'Twinkle';
		Twinkle.defaultConfig.portletType = null;
		Twinkle.defaultConfig.portletNext = 'p-userpagetools';
		break;
	default:
		Twinkle.defaultConfig.portletArea = null;
		Twinkle.defaultConfig.portletId = 'p-cactions';
		Twinkle.defaultConfig.portletName = null;
		Twinkle.defaultConfig.portletType = null;
		Twinkle.defaultConfig.portletNext = null;
}
```

## Tests

I don't see a single test for this complex code. A refactor should probably add in some tests.

**Comment by jdlrobson** [comment]
hey all the API is now on the beta cluster if you want to try it out https://en.wikipedia.beta.wmflabs.org/wiki/Spain
(it's also available in a buggy form on en.wikipedia.org)

I think the function should be useful as is and be more robust than your current code, but just a note that there is still not native support for dropdowns (follow https://phabricator.wikimedia.org/T342815 for that).

```
var useCactions = [ 'monobook', 'cologneblue', 'modern' ].indexOf( mw.config.get( 'skin' ) ) > -1;
var portletId = useCactions ? 'p-cactions' : 'p-twinkle';
var p;
if ( !$( portletId ).length ) {
    p = mw.util.addPortlet(portletId, 'TW' );
    $( p ).insertAfter( '#p-cactions' );
}
mw.util.addPortletLink( portletId, '#', 'csd', 'tw-csd' );
mw.util.addPortletLink( portletId, '#', 'prod', 'tw-prod' );
mw.util.addPortletLink( portletId, '#', 'xfd', 'tw-xfd' );
mw.util.addPortletLink( portletId, '#', 'rpp', 'tw-rpp' );
mw.util.addPortletLink( portletId, '#', 'tag', 'tw-tag' );
mw.util.addPortletLink( portletId, '#', 'last', 'tw-last' );
mw.util.addPortletLink( portletId, '#', 'unlink', 'tw-unlink' );

```

For the dropdowns in the mean time you'll need to keep your custom code until we work out the details of https://phabricator.wikimedia.org/T342815.

Here's some lightweight code that could be used:
```
function vector22Dropdown( portlet ) {
    var $cloneDropdown = $( '#vector-page-tools-dropdown' ).clone();
    $cloneDropdown.attr( 'id', 'twinkle-dropdown' );
    var $chkBox = $cloneDropdown.find( 'input' );
    $chkBox.attr( {
        id: 'twinkle-checkbox',
        'data-event-name': 'twinkle'
    } );
    var $label = $( portlet ).find( '.vector-menu-heading' );
    var $chkLabel = $cloneDropdown.find( 'label' );
    $cloneDropdown.find( 'label' ).attr( {
        id: 'twinkle-dropdown-label',
        for: 'twinkle-checkbox'
    } ).text( $label.text() );
    $label.remove();
    $cloneDropdown.find( '.vector-dropdown-content' ).empty().append( portlet );
    $cloneDropdown.appendTo( '#right-navigation' );
}

function vectorDropdown( portlet ) {
    portlet.classList.add( 'vector-menu-dropdown' );
    portlet.classList.remove( 'vector-menu-portal' );
}


var useCactions = [ 'monobook', 'cologneblue', 'modern' ].indexOf( mw.config.get( 'skin' ) ) > -1;
var portletId = useCactions ? 'p-cactions' : 'p-twinkle';
var p;
if ( !$( portletId ).length ) {
    p = mw.util.addPortlet(portletId, 'TW' );
    $( p ).insertAfter( '#p-cactions' );
}
mw.util.addPortletLink( portletId, '#', 'csd', 'tw-csd' );
mw.util.addPortletLink( portletId, '#', 'prod', 'tw-prod' );
mw.util.addPortletLink( portletId, '#', 'xfd', 'tw-xfd' );
mw.util.addPortletLink( portletId, '#', 'rpp', 'tw-rpp' );
mw.util.addPortletLink( portletId, '#', 'tag', 'tw-tag' );
mw.util.addPortletLink( portletId, '#', 'last', 'tw-last' );
mw.util.addPortletLink( portletId, '#', 'unlink', 'tw-unlink' );

if ( p && mw.config.get( 'skin' ) === 'vector-2022' ) {
    vector22Dropdown( p );
}

if ( p && mw.config.get( 'skin' ) === 'vector' ) {
    vectorDropdown( p );
}
```

Let me know what you need!`

**Comment by NovemLinguae** [comment]
WMF web team says `mw.util.addPortlet()` is ready for use now. https://phabricator.wikimedia.org/T342815#9303586

**Comment by NovemLinguae** [comment]
P.S. Dropdowns are now supported by the `mw.util.addPortlet()` function. https://phabricator.wikimedia.org/T342815
