### ISSUE TITLE
speedy: if {{Being deleted}} template present, auto-select CSD G6 XFD and fill the text box

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1845]
Requested by Izno at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Feature_request_for_a_papercut%3A_Support_Template%3ABeing_deleted_as_if_it_were_a_CSD_tag

Pre-fill "page where the deletion discussion was held" based on the contents of the first parameter of the template.

The pre-selection of G6 XFD and "page where the deletion discussion was held" should probably persist even if the user checks or unchecks "tag page only, don't delete". Experiment with that.

![image](https://github.com/wikimedia-gadgets/twinkle/assets/79697282/65797abf-363c-472c-b5c9-c1ff15ca4dbf)

![image](https://github.com/wikimedia-gadgets/twinkle/assets/79697282/fbe75ddf-5c02-4f57-aac2-0f40599a0ad9)

**Comment by primefac** [comment]
Agreed on the last point; about the only thing someone (i.e. a non-admin) would be tagging the page for would be G6 for that reason.

**Comment by NovemLinguae** [comment]
<img width="996" alt="image" src="https://github.com/wikimedia-gadgets/twinkle/assets/79697282/b654ae34-9c60-47fa-8795-36ffa5c33306">

**Comment by NovemLinguae** [comment]
Sounds like this was implemented at the template level. Closing as complete.
