### ISSUE TITLE
tag: Twinkle doesn't detect {{More footnotes needed}}

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1863]
Steps to reproduce
* https://en.wikipedia.org/w/index.php?title=Montgomery_Riverfront_brawl&oldid=1174308453 (which includes the wikicode `{{More footnotes needed|date=September 2023}}`)
* TW->Tag
* uncheck {{More footnotes}}
* type "sufficient citations" for the reason
* click "submit query"

What happens?
<img width="726" alt="image" src="https://github.com/wikimedia-gadgets/twinkle/assets/79697282/81ce96e9-2bbb-4368-905f-1dfa1ebd030a">

**Comment by 9382** [comment]
I'll also note I've just seen #1618 which appears to be the exact same bug
