### ISSUE TITLE
submit button: change "Submit Query" to "Submit"

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1864]
"Submit Query" reminds me of querying an SQL database.

For submitting an HTML form, "Submit" should do fine.

Looks like this is some default text in Morebits.

`button.textContent = msg('submit', 'Submit Query');`

If not overridden, it shows up in modules such as Tag, RFPP, etc.

<img width="304" alt="image" src="https://github.com/wikimedia-gadgets/twinkle/assets/79697282/496195d7-ac20-4cad-abc1-06a63a2454b5">

**Comment by ATREAY** [comment]
Hey @NovemLinguae ,

Since I'm just getting started with open source, can I take this issue?

**Comment by NovemLinguae** [comment]
Sure. After writing the patch, don't forget to test using the instructions at https://github.com/wikimedia-gadgets/twinkle/blob/master/CONTRIBUTING.md#testing-your-code

**Comment by ATREAY** [comment]
Of course @NovemLinguae, I'll make the necessary changes, test it out, and then I'll reach out to you with the updates.

**Comment by ATREAY** [comment]
Hello @NovemLinguae,

I have implemented the required modifications. Please take a moment to review them.

**Comment by NovemLinguae** [comment]
Thanks for the PR. FYI, things move pretty slow around here. I will get to your PR eventually but am currently busy IRL.

**Comment by ATREAY** [comment]
Hey @NovemLinguae,

No problem at all. Feel free to check out this pull request whenever you have some free time.

**Comment by ATREAY** [comment]
Hello @NovemLinguae,
I would like to kindly request your assistance in reviewing my pull request, which has been open for two weeks.

**Comment by NovemLinguae** [comment]
Sorry, busy with day job this week. I tend to get a burst of energy and clear the PR queue ever couple months. Things move a bit slowly around here.

**Comment by siddharthvp** [comment]
Resolved by #1865
