### ISSUE TITLE
module file names should not start with "twinkle" and "friendly"

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1920]
Should shorten the names of these files at some point.

In particular, the 4 that start with friendly cause my eyes to look in the wrong place in the list since I usually assume the module starts with twinkle.

But in general it would be good to shorten the filenames.

<img width="127" alt="image" src="https://github.com/wikimedia-gadgets/twinkle/assets/79697282/9e0e393b-34b8-48e9-962f-e9723cc00bf4">

**Comment by sohelhussain** [comment]
@NovemLinguae So do I have to name it Twinkle instead of Friendly?

**Comment by sohelhussain** [comment]
his @NovemLinguae how to I'll write a shorten name give me a some example. and what's the giving a name ? rather than "twinkle" and "friendly".

**Comment by NovemLinguae** [comment]
Duplicate of #1974
