### ISSUE TITLE
speedy: update U5

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1930]
Requested by SmokeyJoe at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#U5_wording

Update the below

```js
	{
		label: 'U5: Blatant WP:NOTWEBHOST violations',
		value: 'notwebhost',
		tooltip: 'Pages in userspace consisting of writings, information, discussions, and/or activities not closely related to Wikipedia\'s goals, where the owner has made few or no edits outside of userspace, with the exception of plausible drafts and pages adhering to WP:UPYES.',
		hideWhenRedirect: true
	},
```

to more closely match https://en.wikipedia.org/wiki/Wikipedia:Criteria_for_speedy_deletion#U5._A_non-contributor's_misuse_of_Wikipedia_as_a_web_host

SmokeyJoe suggested this label: "U5: A non-contributor violating WP:NOTWEBHOST"

I would also recommend updating the tooltip with the text at https://en.wikipedia.org/wiki/Wikipedia:Criteria_for_speedy_deletion#U5._A_non-contributor's_misuse_of_Wikipedia_as_a_web_host

## Acceptance criteria ##
* [ ] update U5 label
* [ ] update U5 tooltip

**Comment by pppery** [comment]
It would also be nice to enforce the rule that the user is a non-contributor on tagging - I just declined a U5 page tagged with Twinkle where the user had 3000 edits 90% of which were to mainspace.

**Comment by RustyBust** [comment]
I know I just commented on #1972, but this task also seems simple enough that I'd like to be assigned to this too.

**Comment by NovemLinguae** [comment]
Sure. Feel free to write a PR for any open ticket. You can work on any ticket whether it's assigned or not.

Warning: patches will sit for awhile. I catch up on them in batches every 6 months or so.
