### ISSUE TITLE
Marking CSD-ed pages as reviewed

### ISSUE THREAD

**Issue by TechnoSquirrel69** [wikimedia-gadgets/twinkle#1934]
Twinkle just marked as reviewed the redirect that I tagged for R2 deletion. It probably shouldn't do that. If it helps at all, [here's the log entry](https://en.wikipedia.org/w/index.php?title=Special:Log&logid=158413754).

**Comment by TechnoSquirrel69** [comment]
![image](https://github.com/wikimedia-gadgets/twinkle/assets/147560416/65b5dbf1-1a81-497f-826a-abf3f5851831)
Reproduced and got a screenshot this time.

**Comment by TechnoSquirrel69** [comment]
Issue seems to be resolved; the last R2 tag I added did not automatically get marked as reviewed.

**Comment by TechnoSquirrel69** [comment]
Never mind, it's back again. No idea why it's doing it inconsistently.

**Comment by TechnoSquirrel69** [comment]
So Twinkle just [marked a G12 as reviewed](https://en.wikipedia.org/w/index.php?title=Special:Log&logid=159171049). I think there's some functionality somewhere that needs to be adjusted to disable the automatic reviewing of pages for _any_ of the CSDs.

**Comment by NovemLinguae** [comment]
This is probably the reason: https://en.wikipedia.org/wiki/User:TechnoSquirrel69/twinkleoptions.js#L-37

Have you tried adjusting your Twinkle settings at https://en.wikipedia.org/wiki/Wikipedia:Twinkle/Preferences and unticking "CSD" -> "Mark page as patrolled/reviewed when tagging (if possible)"?

**Comment by TechnoSquirrel69** [comment]
**Self-trout**. I had checked through my preferences when I first opened this ticket, but I guess I missed that option? Anyways, is there a reason why Twinkle has a preference to automatically mark a page as reviewed when using the CSD module? Correct me if I'm wrong, but I don't think it's common practice to mark a page as reviewed for any of the speedy criteria.

**Comment by NovemLinguae** [comment]
https://en.wikipedia.org/w/index.php?search=insource%3A%22markSpeedyPagesAsPatrolled%3A%5C%22%3A+true%22&title=Special:Search&profile=advanced&fulltext=1&ns2=1

316 Twinkle users appear to have this setting turned on, so it would probably be too disruptive to remove it. Although I agree with your line of thinking.
