### ISSUE TITLE
tag: add {{User-generated}}, {{BLP one source}}, {{BLP no footnotes}}

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1972]
Requested by Jlwoodwa at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Tags_for_user-generated_and_BLP_reference_issues

**Comment by RustyBust** [comment]
I'd like to work on this task as a first contributor when I have the time.

**Comment by fredster33** [comment]
@NovemLinguae this should probably be closed now :)
