### ISSUE TITLE
remove "twinkle" and "friendly" from module names

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1974]
- overly verbose
- makes alphabetizing difficult

Should probably work on and merge this patch after clearing out the PR queue, to avoid a bunch of merge conflicts.

![image](https://github.com/wikimedia-gadgets/twinkle/assets/79697282/e70c208c-68ea-4f6d-a2d4-9f2e9bd3d804)

**Comment by nardog** [comment]
While you're at it, consider renaming "fluff" too, I've found it confusing and opaque.

**Comment by NovemLinguae** [comment]
Note to self: scripts/draftRelease.sh, scripts/sync.pl, and MediaWiki:Gadgets-definition contain lists of Twinkle files that will need to be updated.

**Comment by NovemLinguae** [comment]
I think I've changed my mind about this ticket. Removing "twinkle" from the beginning of the module names would make CirrusSearch search suggestions worse, and would break the convention of prefixing gadget files with the name of the gadget.

<img width="228" alt="image" src="https://github.com/user-attachments/assets/821a33de-a8d5-447a-81b9-a3286ab07c1d">

Perhaps I will re-scope this ticket to rename "friendly" to "twinkle".

**Comment by NovemLinguae** [comment]
Closing in favor of #1995
