### ISSUE TITLE
rename "twinklefluff.js" to "twinklerollback.js"

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1975]
Unlike the other module names, "fluff" is not descriptive of what the module does. The word is meaningless to new devs

Thanks to @nardog for the idea.

**Comment by RustyCat-1** [comment]
@NovemLinguae Do you want the file only to be renamed, or should the module also be renamed (from `Twinkle.fluff` to `Twinkle.rollback`)?

**Comment by NovemLinguae** [comment]
I'm thinking the module too please.

**Comment by RustyCat-1** [comment]
I believe I have the module renamed most of the way, but I'd like to make sure that both `fluff` and `rollback` in `Twinkle.disabledModules` (on config) make the checkbox checked and I'm not quite sure how to do that. (I thought about adding a condition for checking that specific checkbox, but I don't think that's a good idea.
