### ISSUE TITLE
Fix issues in Vector 2022 dark mode

### ISSUE THREAD

**Issue by thewub** [wikimedia-gadgets/twinkle#1979]
Steps to reproduce:

- Use Vector 2022 skin
- In https://en.wikipedia.org/wiki/Special:Preferences#mw-prefsection-betafeatures enable "Accessibility for Reading (Vector 2022)"
- Switch Color to Dark in the Appearance panel
- Use a function in Twinkle

Result:
There are some issues with bits of text being unreadable, forms having a dark background which doesn't fit with the rest of the design
![en wikipedia org_wiki_User_The_wub](https://github.com/wikimedia-gadgets/twinkle/assets/4460801/0f41bdbf-2d02-4d19-95d1-4acb5f7887e6)
![en wikipedia org_wiki_User_The_wub (1)](https://github.com/wikimedia-gadgets/twinkle/assets/4460801/a6fde9ac-e1d3-4a49-ad2f-b1be28e7992a)

I think most of the issues can be fixed by just adding the class "notheme" on the dialog and any other associated elements (as described at https://www.mediawiki.org/wiki/Recommendations_for_night_mode_compatibility_on_Wikimedia_wikis)

**Comment by NovemLinguae** [comment]
Convenience links for testing:

* https://test.wikipedia.org/wiki/User_talk:NovemBot?useskin=vector-2022&vectornightmode=1
* https://test.wikipedia.org/wiki/Mainspace?useskin=vector-2022&vectornightmode=1
* https://test.wikipedia.org/wiki/Wikipedia:Twinkle/Preferences?useskin=vector-2022&vectornightmode=1

**Comment by Sky2042** [comment]
twinkle-config-headerbox that display in user/common.js could use a dark treatment. 
![image](https://github.com/user-attachments/assets/e2ba7e9e-5c71-4174-9fda-fbdf734b9229)
