### ISSUE TITLE
don't place templates on pages using non-wikitext content models

### ISSUE THREAD

**Issue by TechnoSquirrel69** [wikimedia-gadgets/twinkle#2018]
Twinkle should ideally avoid placing deletion templates (or any other templates, for that matter) on pages that use a content model other that wikitext. See [this edit](https://en.wikipedia.org/w/index.php?title=TimedText:It%27s_just_a_burning_memory_-_sample.ogg.en.srt&diff=prev&oldid=1250716165), which introduces the {{MfD}} template into a TimedText file.

![image](https://github.com/user-attachments/assets/7c94c97f-72aa-40e7-b5fd-2b8a0abaf629)

**Comment by pppery** [comment]
Note that TimedText pages are considered by MediaWiki to have content model wikitext, even though they clearly don't.
