### ISSUE TITLE
talkback: do not mark user talk messages as minor edits

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#2032]
Reported by Miraclepine at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Noticeboard_notifications_are_marked_as_minor_edits

In diffs such as https://en.wikipedia.org/wiki/Special:Diff/1252810183, the edit should not be marked as minor, since it is a message, rather than something actually minor like gnoming, typo correction, etc.

**Comment by DreamRimmer** [comment]
![Screenshot 2024-11-07 171212](https://github.com/user-attachments/assets/5001e112-5dfc-4765-868e-292c6ffcbab1)
Users can change this setting in the Twinkle preferences.

**Comment by NovemLinguae** [comment]
Thanks DR. Good find.

Looks like it defaults to on. Maybe the solution to this ticket should be to change it to default to off.

<img width="250" alt="image" src="https://github.com/user-attachments/assets/7e28cd94-55d1-4ab5-907f-9fc4f62177e0">
