### ISSUE TITLE
welcome: add some {{Welcomeen-XX}} templates

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#2038]
Requested by I dream of horses at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Adding_other_Welcomeen_templates_to_the_default_configuration

* {{[subst:Welcomeen-ha](https://en.wikipedia.org/wiki/Template:Welcomeen-ha)}} (Hausa)
* {{[subst:Welcomeen-hi](https://en.wikipedia.org/wiki/Template:Welcomeen-hi)}} (Hindi)
* {{[subst:Welcomeen-id](https://en.wikipedia.org/wiki/Template:Welcomeen-id)}} (Indonesian)
* {{[subst:Welcomeen-it](https://en.wikipedia.org/wiki/Template:Welcomeen-it)}} (Italian)
* {{[subst:Welcomeen-ms](https://en.wikipedia.org/wiki/Template:Welcomeen-ms)}} (Malay)
* {{[subst:Welcomeen-fa](https://en.wikipedia.org/wiki/Template:Welcomeen-fa)}} (Persian)
* {{[subst:Welcomeen-th](https://en.wikipedia.org/wiki/Template:Welcomeen-th)}} (Thai)
* {{[subst:Welcomeen-ur](https://en.wikipedia.org/wiki/Template:Welcomeen-ur)}} (Urdu)
* {{[subst:Welcomeen-vi](https://en.wikipedia.org/wiki/Template:Welcomeen-vi)}} (Vietnamese)

**Comment by fredster33** [comment]
{{subst:welcomeen-tr}} (Turkish) too

**Comment by fredster33** [comment]
It looks like {{[subst:Welcomeen-hi](https://en.wikipedia.org/wiki/Template:Welcomeen-hi)}} (Hindi) is already in Twinkle

**Comment by fredster33** [comment]
Full list of languages added:
{{subst:Welcomeen-fa}} (Persian)
{{subst:Welcomeen-ha}} (Hausa)
{{subst:Welcomeen-id}} (Indonesian)
{{subst:Welcomeen-it}} (Italian)
{{subst:Welcomeen-ms}} (Malay)
{{subst:Welcomeen-no}} (Norwegian)
{{subst:Welcomeen-pl}} (Polish)
{{subst:Welcomeen-th}} (Thai)
{{subst:Welcomeen-tl}} (Tagalog)
{{subst:welcomeen-tr}} (Turkish)
{{subst:Welcomeen-ur}} (Urdu)
{{subst:Welcomeen-vi}} (Vietnamese)
