### ISSUE TITLE
tag: prevent placing the same tag twice

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#2046]
Steps to reproduce
* create a page with wikitext Test
* tag it {{Promotional}}
* tag it {{Promotional}} again

What happens?
* tag is added twice. https://test.wikipedia.org/w/index.php?title=Mainspace&diff=prev&oldid=624484

What should happen instead?
* tag is detected and its check box is ticked
* no wikicode is written

**Comment by siddharthvp** [comment]
Does this occur on enwiki too? I'm guessing on enwiki where the template actually exists, it would show up under "Tags already present" so it only possible to untag it, not tag it again.

**Comment by NovemLinguae** [comment]
Ah, you're right. I always forget that Twinkle does tag detection based on HTML and not wikitext. Is counter intuitive to me so my brain keeps forgetting it. Anyway, that makes this an unusual case then, and probably not worth a ticket. Closing.
