### ISSUE TITLE
Check for existing Sockpuppet investigations 

### ISSUE THREAD

**Issue by sjvolkmann** [wikimedia-gadgets/twinkle#2080]
As a new feature, Twinkle should check for existing Sockpuppet investigations before submitting the API query to avoid duplicates like this one:

https://en.wikipedia.org/w/index.php?title=Wikipedia:Sockpuppet_investigations/Antonio66555&diff=prev&oldid=1259480295

**Comment by NovemLinguae** [comment]
Good idea. This appears to be a duplicate of #1496 though, so will close for now. Feel free to re-open if I'm mistaken.
