### ISSUE TITLE
Requesting help to update eswiki's Twinkle installation

### ISSUE THREAD

**Issue by MarcoAurelioWM** [wikimedia-gadgets/twinkle#389]
https://es.wikipedia.org/wiki/Wikipedia:Twinkle

We still use TwinkleUser, etc... outdated stuff.

It'd be good if we could re-enable the gadget over there to help new page patrol.

Willing to help on what I can do.

Thank you!

**Comment by DannyS712** [comment]
@MarcoAurelioWM is this still needed? And, if it is, what is the difference between eswiki and enwiki installations, other than the internationalization and changing page names, etc.?

**Comment by MarcoAurelioWM** [comment]
Hello. Yes, I think this is still needed given that we're still [loading outdated code](https://es.wikipedia.org/wiki/Usuario:TwinkleUser/twinkle.js) and have several functions not working. Let me ask some tecnical people from eswiki and I'll try to get back to you as soon as possible. Best regards.

**Comment by QEDK** [comment]
I haven't checked the code but if it's a very old release, it's better to start afresh. I've attempted maintaining some languages myself and it's impossible without someone experienced at the homewiki porting changes occasionally.

**Comment by nasch92** [comment]
Hi. I'm now developing a lightweight jQuery-less version of Twinkle [here](https://github.com/nasch92/twinkle-lite). I'm using [webPack](https://webpack.js.org/) to have all the modules pressed together into one single file. I'm not a programmer by profession so it might take me some time and I'm aware there might be some things that could be implemented more effectively, though. As of now the available modules are deletion requests, page protection and speedy deletion. If anyone is interested in collaborating feel free to come over :heart:.

**Comment by siddharthvp** [comment]
@nasch92 Looks good, but you appear to be using morebits, which is based on jquery.ui. So it's not "jQuery-less" :)

**Comment by nasch92** [comment]
> @nasch92 Looks good, but you appear to be using morebits, which is based on jquery.ui. So it's not "jQuery-less" :)

Oh... haha... I had no idea. I guess that gives you an idea how little I know. Not gonna lie it's been a struggle so far.

**Comment by nacaru-w** [comment]
@siddharthvp @NovemLinguae I think this issue can now be closed as [Twinkle Lite](https://es.wikipedia.org/wiki/Wikipedia:Twinkle_Lite) is up and running on eswiki ([repo here](https://github.com/nacaru-w/twinkle-lite)).

@MarcoAurelioWM if you have some spare time to have a look at the [request](https://es.wikipedia.org/wiki/Wikipedia:Administradores_de_interfaz/Tabl%C3%B3n_de_solicitudes#A%C3%B1adir_Twinkle_Lite_a_la_lista_de_accesorios_que_se_pueden_activar_desde_la_configuraci%C3%B3n) I made at the interface admin board, the tool could be activated from user settings. As of now it only works through modification of the `common.js` page.
