### ISSUE TITLE
Rollback should treat IPv6 users in the same /64 as one user

### ISSUE THREAD

**Issue by pppery** [wikimedia-gadgets/twinkle#924]
> It also would be nice if Twinkle rollback reverted IPv6 edits on the basis of the /64, vandalism by a IPv6 switching withing its /64 range often gets left in. 

[Eostrix at Wikipedia:Village pump (technical)](https://en.wikipedia.org/wiki/Special:Diff/951300234)

**Comment by QEDK** [comment]
Don't think Twinkle should implement this before MediaWiki actually implements this - https://phabricator.wikimedia.org/T112325

**Comment by siddharthvp** [comment]
> Don't think Twinkle should implement this before MediaWiki actually implements this

lol no, MediaWiki could take a decade to implement that. We don't need to wait for that. We are already stuff in rollback that MediaWiki doesn't, like the bot whitelist thing.

**Comment by QEDK** [comment]
> > Don't think Twinkle should implement this before MediaWiki actually implements this
> 
> lol no, MediaWiki could take a decade to implement that. We don't need to wait for that. We are already doing stuff in rollback that MediaWiki doesn't, like the bot whitelist thing.

Yes, but there's still the implication of policy. **Usually**, /64 are the smallest ranges assigned to end-users but it's also possible to assign it to small companies, large households and other institututions. We should not assume all /64 are the same user and this is reflected in MediaWiki docs as of now:

> Like in IPv4, where a single static IPv4 address may supply a household or institution of some kind, a static IPv6 /64 range may also supply a household or institution, so multiple users can be affected by /64 rangeblocks.

So, until there is a reasonable consensus that /64 should be treated as one user (a MediaWiki core change would signify that, for e.g.), no reason for Twinkle to change the status quo.

**Comment by martijnhoekstra** [comment]
> no reason for Twinkle to change the status quo.

This would be totally true if the status quo were workable.

**Comment by Eostrix77** [comment]
Twinkle rollback should be independent of the MediaWiki question.

In Combing talk pages on MediaWiki for the /64 (a good safe thing, but... forever) you want to be fairly certain that project-wide, in totally different pages, the same /64 is the same, or that the shared IP benefits (messages actually arriving) outweighs any possible drawback.

Twinkle rollback poses a much NARROWER question: whether CONSECUTIVE edits by the SAME /64 to the SAME ARTICLE are likely to be the same person. The answer to that is probably 99.999% yes, and it is a much easier question to answer yes to than the MediaWiki project-wide combining.

**Comment by Amorymeltzer** [comment]
> whether CONSECUTIVE edits by the SAME /64 to the SAME ARTICLE are likely to be the same person. The answer to that is probably 99.999% yes...

Yes.  This is I think the only thing for Twinkle to do as regards this, and I do think it's a good idea.  Trying to do something with leaving warnings (or even interacting with the talkpae in general) would be a whole host of issues.  See also #775
